### ISSUE TITLE
Incompatible with rails 5.0.0.1

### ISSUE THREAD

**Issue by maiconsanson** [rails/actionpack-action_caching#39]
```
Bundler could not find compatible versions for gem "actionpack":
  In snapshot (Gemfile.lock):
    actionpack (= 5.0.0.1)

  In Gemfile:
    actionpack-action_caching was resolved to 1.1.1, which depends on
      actionpack (< 5.0, >= 4.0.0)
```

**Comment by jasnow** [comment]
+1

**Comment by sergiotapia** [comment]
Is there anything we can do here?

**Comment by MichalHlavacek** [comment]
Using 
`gem 'actionpack-action_caching', :git => 'https://github.com/rails/actionpack-action_caching'` 
in Gemfile will fix it for you. Rubygems version has actionpack dependency problem.

**Comment by pixeltrix** [comment]
Closing because this is fixed already

**Comment by jastkand** [comment]
@pixeltrix it wasn't fixed for me. I still have to use the version directly from the github.
